# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 14:45
from __future__ import unicode_literals

from django.db import migrations

def load_default(apps, schema_editor):
    Setting = apps.get_model("instanalysis", "Setting")
    s = Setting(name='access_token', value='3093109113.2bfbe74.30fb845c423a481e81086f4b6f68a6c7')
    s.save()
    s = Setting(name='instagram_code', value='3c8189905626401b9b16dc7ad177c7fa')
    s.save()
    s = Setting(name='next_max_id', value='')
    s.save()
    s = Setting(name='next_min_id', value='')
    s.save()
    s = Setting(name='last_photo_update', value='')
    s.save()
    s = Setting(name='instagram_hourly', value='0')
    s.save()
    s = Setting(name='interval_updates', value='2', help='Interval between updating locations (minutes)')
    s.save()

def destroy_defaults(apps, schema_editor):
    Settings = apps.get_model("instanalysis", "Setting")
    for cf in Settings.objects.all():
        cf.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(load_default, destroy_defaults)
    ]
