# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 13:48
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0003_city_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='city',
            name='zoom',
            field=models.PositiveIntegerField(default=6),
            preserve_default=False,
        ),
    ]
