# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 13:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0004_auto_20160513_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
