# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0005_auto_20160513_1549'),
    ]

    operations = [

    ]
