# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 14:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0006_auto_20160513_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='instagramlocation',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
        migrations.AlterField(
            model_name='spot',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
