# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0009_auto_20160517_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramlocation',
            name='next_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instagramlocation',
            name='latest_media_id',
            field=models.CharField(blank=True, help_text=b'Last id obtained, useful for pagination', max_length=256, null=True),
        ),
    ]
