# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0011_remove_instagramlocation_next_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramuser',
            name='instagramID',
            field=models.CharField(max_length=300),
        ),
    ]
