# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0012_auto_20160517_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='caption',
            field=models.CharField(max_length=2200, null=True),
        ),
    ]
