# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0013_auto_20160517_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramlocation',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
