# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import instanalysis.utils


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0014_instagramlocation_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramlocation',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=instanalysis.utils._get_init_datetime_location, null=True),
        ),
    ]