# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0017_auto_20160615_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocsearch',
            name='status',
            field=models.CharField(choices=[(0, b'In progress'), (1, b'Completed')], default=0, max_length=1),
        ),
    ]
