# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0018_auto_20160615_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocsearch',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='instanalysis.Category'),
        ),
        migrations.AlterField(
            model_name='adhocsearch',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, to='instanalysis.Hashtag'),
        ),
        migrations.AlterField(
            model_name='adhocsearch',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adhocsearch',
            name='slotrange',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adhocsearch',
            name='weekday',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
