# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0019_auto_20160615_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocsearch',
            name='query_url',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
