# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0020_adhocsearch_query_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='is_adhoc',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spot',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instanalysis.City'),
        ),
    ]
