# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0023_auto_20160616_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[(0, b'In progress'), (1, b'Completed')], default=0, max_length=1)),
                ('url_file', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
