# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-17 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0024_exportform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocsearch',
            name='status',
            field=models.CharField(choices=[(0, b'In progress'), (1, b'Completed'), (2, b'Error')], default=0, max_length=1),
        ),
    ]
