# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0026_auto_20160717_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='label',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
    ]
