# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0027_auto_20160717_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instagramlocation',
            options={'ordering': None},
        ),
    ]
