# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instanalysis', '0028_auto_20160717_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocsearch',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
